//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSComputersMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bid()
        {
            this.Workorders = new HashSet<Workorder>();
        }
    
        public int BidID { get; set; }
        public Nullable<System.DateTime> BidDate { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public int CustomerID { get; set; }
        public string Description { get; set; }
        public int EmployeeID { get; set; }
        public string Status { get; set; }
        public string ContractType { get; set; }
        public Nullable<decimal> ContractAmount { get; set; }
        public Nullable<int> PartsMarkup { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workorder> Workorders { get; set; }
    }
}
