//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSComputersMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int CustomerID { get; set; }
        public string Description { get; set; }
        public int EmployeeID { get; set; }
        public decimal InvoiceTotal { get; set; }
        public string ContractType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
