//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSComputersMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workorder
    {
        public int WorkorderID { get; set; }
        public System.DateTime WorkorderDate { get; set; }
        public Nullable<int> BidID { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public int CustomerID { get; set; }
        public string Description { get; set; }
        public int EmployeeID { get; set; }
        public string WorkOrderStatus { get; set; }
        public string ContractType { get; set; }
        public Nullable<decimal> ContractAmount { get; set; }
        public Nullable<int> PartsMarkup { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
    
        public virtual Bid Bid { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
