//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSComputersMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderHour
    {
        public int WorkorderID { get; set; }
        public System.DateTime Date { get; set; }
        public int EmployeeID { get; set; }
        public int HoursBid { get; set; }
        public Nullable<decimal> PricePerHour { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
